spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cash register
    driver: org.postgresql.Driver
    username: postgres
    password: root

  hibernate:
    dialect: org.hibernate.dialect.PostgreSQL10Dialect
    show_sql: true
    format_sql: true
    physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

  liquibase:
    change-log: classpath:db/changelog/db-changelog-1.xml

  log4j2: